ifpe-cti/petpalacy

src/main/java/br/edu/ifpe/petshop/model/entidades/Cliente.java, src/main/java/br/edu/ifpe/petshop/model/entidades/Endereco.java
@DanielCalado Criação da classe cliente que terá todos os atributos necessários para o cadastro do cliente, criação da classe endereço, a qual sera utilizada como atributo composto da classe Cliente.
=> #13 criação das classes relacionadas ao cadastro do cliente

src/main/java/br/edu/ifpe/petshop/model/entidades/Agendamento.java, src/main/java/br/edu/ifpe/petshop/model/entidades/Cliente.java, src/main/java/br/edu/ifpe/petshop/model/entidades/Servico.java
Adicionei os atributos email e senha a classe cliente.
=> Conforme a issue #13

src/main/java/br/edu/ifpe/petshop/infraestrutura/dao/PersistenciaDAO.java, src/main/java/br/edu/ifpe/petshop/infraestrutura/repositorio/implementacao/RepositorioAgendamentoDB.java, src/main/java/br/edu/ifpe/petshop/infraestrutura/repositorio/implementacao/RepositorioClienteDB.java, src/main/java/br/edu/ifpe/petshop/infraestrutura/repositorio/implementacao/RepositorioServicoDB.java, src/main/java/br/edu/ifpe/petshop/infraestrutura/repositorio/interfaces/RepositorioGenerico.java, src/main/java/br/edu/ifpe/petshop/util/HibernateUtil.java
=> Revert "#26 licença colocada."

src/main/java/br/edu/ifpe/petshop/infraestrutura/dao/PersistenciaDAO.java, src/main/java/br/edu/ifpe/petshop/infraestrutura/repositorio/implementacao/RepositorioAgendamentoImpDB.java, src/main/java/br/edu/ifpe/petshop/infraestrutura/repositorio/implementacao/RepositorioClienteImpDB.java, src/main/java/br/edu/ifpe/petshop/infraestrutura/repositorio/implementacao/RepositorioEmpresaImpDB.java, src/main/java/br/edu/ifpe/petshop/infraestrutura/repositorio/implementacao/RepositorioServicoImpDB.java, src/main/java/br/edu/ifpe/petshop/infraestrutura/repositorio/interfaces/RepositorioAgendamento.java, src/main/java/br/edu/ifpe/petshop/infraestrutura/repositorio/interfaces/RepositorioCliente.java, src/main/java/br/edu/ifpe/petshop/infraestrutura/repositorio/interfaces/RepositorioEmpresa.java, src/main/java/br/edu/ifpe/petshop/infraestrutura/repositorio/interfaces/RepositorioGenerico.java, src/main/java/br/edu/ifpe/petshop/infraestrutura/repositorio/interfaces/RepositorioServico.java, src/main/java/br/edu/ifpe/petshop/util/HibernateUtil.java
=> Adição das classes de conexão com o banco.

src/main/java/br/edu/ifpe/petshop/Teste.java, src/main/java/br/edu/ifpe/petshop/model/entidades/Agendamento.java, src/main/java/br/edu/ifpe/petshop/model/entidades/DatasServico.java, src/main/java/br/edu/ifpe/petshop/model/entidades/Empresa.java, src/main/java/br/edu/ifpe/petshop/model/entidades/Servico.java, src/main/java/br/edu/ifpe/petshop/model/repositorio/implementacao/RepositorioAgendamentoImpDB.java, src/main/java/br/edu/ifpe/petshop/model/repositorio/implementacao/RepositorioClienteImpDB.java, src/main/java/br/edu/ifpe/petshop/model/repositorio/implementacao/RepositorioEmpresaImpDB.java, src/main/java/br/edu/ifpe/petshop/model/repositorio/implementacao/RepositorioServicoImpDB.java, src/main/java/br/edu/ifpe/petshop/model/repositorio/interfaces/RepositorioCliente.java, src/main/java/br/edu/ifpe/petshop/model/repositorio/interfaces/RepositorioEmpresa.java, src/main/resources/hibernate.cfg.xml
=> Correção de erros 

src/main/java/br/edu/ifpe/petshop/model/entidades/Empresa.java, src/main/java/br/edu/ifpe/petshop/model/negocio/NegocioEmpresa.java, src/main/java/br/edu/ifpe/petshop/model/negocio/interfaces/EmpresaInterface.java, src/main/java/br/edu/ifpe/petshop/model/negocio/interfaces/NegocioInterface.java, src/main/java/br/edu/ifpe/petshop/model/repositorio/implementacao/RepositorioEmpresaImpDB.java, src/main/java/br/edu/ifpe/petshop/model/repositorio/interfaces/RepositorioEmpresa.java, src/main/java/br/edu/ifpe/petshop/model/repositorio/interfaces/RepositorioGenerico.java
@DanielCalado De acordo com a issue #40
=> Classe NegocioEmpresa e interfaces

src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioCliente.java, src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioServico.java
=> criacao das classes negocioclinete e negocioservico

src/main/java/br/edu/ifpe/petpalacy/Teste.java, src/main/java/br/edu/ifpe/petpalacy/model/dao/PersistenciaDAO.java, src/main/java/br/edu/ifpe/petpalacy/model/interfaces/InterfaceAgendamento.java, src/main/java/br/edu/ifpe/petpalacy/model/interfaces/InterfaceCliente.java, src/main/java/br/edu/ifpe/petpalacy/model/interfaces/InterfaceEmpresa.java, src/main/java/br/edu/ifpe/petpalacy/model/interfaces/InterfaceServico.java, src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioCliente.java, src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioEmpresa.java, src/main/java/br/edu/ifpe/petpalacy/model/repositorio/implementacao/RepositorioAgendamentoImpDB.java, src/main/java/br/edu/ifpe/petpalacy/model/repositorio/implementacao/RepositorioClienteImpDB.java, src/main/java/br/edu/ifpe/petpalacy/model/repositorio/implementacao/RepositorioEmpresaImpDB.java, src/main/java/br/edu/ifpe/petpalacy/model/repositorio/implementacao/RepositorioServicoImpDB.java
=> Correção de erros relacionados ao novo nome do repositório

src/main/java/br/edu/ifpe/petpalacy/model/entidades/Agendamento.java, src/main/java/br/edu/ifpe/petpalacy/model/entidades/DatasServico.java, src/main/java/br/edu/ifpe/petpalacy/model/entidades/StatusAgen.java, src/main/java/br/edu/ifpe/petpalacy/model/entidades/StatusDataSer.java
=> #52 Correção dos enum

src/main/java/br/edu/ifpe/petpalacy/Teste.java, src/main/java/br/edu/ifpe/petpalacy/model/dao/PersistenciaDAO.java, src/main/java/br/edu/ifpe/petpalacy/model/entidades/Agendamento.java, src/main/java/br/edu/ifpe/petpalacy/model/entidades/Cliente.java, src/main/java/br/edu/ifpe/petpalacy/model/entidades/DatasServico.java, src/main/java/br/edu/ifpe/petpalacy/model/entidades/Servico.java, src/main/java/br/edu/ifpe/petpalacy/model/entidades/StatusDataSer.java, src/main/java/br/edu/ifpe/petpalacy/model/interfaces/InterfaceEmpresa.java, src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioCliente.java, src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioEmpresa.java, src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioServico.java, src/main/java/br/edu/ifpe/petpalacy/model/repositorio/implementacao/RepositorioAgendamentoImplDB.java, src/main/java/br/edu/ifpe/petpalacy/model/repositorio/implementacao/RepositorioClienteImplDB.java, src/main/java/br/edu/ifpe/petpalacy/model/repositorio/implementacao/RepositorioEmpresaImplDB.java, src/main/java/br/edu/ifpe/petpalacy/model/repositorio/implementacao/RepositorioServicoImplDB.java, src/main/resources/hibernate.cfg.xml, src/test/java/be/edu/ifpe/petpalacy/model/dao/PersistenciaDAOExceptoinTest.java, src/test/java/be/edu/ifpe/petpalacy/model/dao/PersistenciaDAOTest.java, src/test/java/br/edu/ifpe/petpalacy/model/repositorio/implementacao/RepositorioAgendamentoImplDBTest.java, src/test/java/br/edu/ifpe/petpalacy/model/repositorio/implementacao/RepositorioClienteImplDBTest.java, src/test/java/br/edu/ifpe/petpalacy/model/repositorio/implementacao/RepositorioEmpresaImplDBTest.java, src/test/java/br/edu/ifpe/petpalacy/model/repositorio/implementacao/RepositorioServicoImplDBTest.java, src/test/java/br/edu/ifpe/petpalacy/util/HibernateUtilTest.java
=> Envio dos Testes

src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioAgendamento.java
=> #60 criação da classe NegocioAgendamento

src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioAgendamento.java, src/main/java/br/edu/petpalacy/controller/ControllerAgendamento.java
@DanielCalado de acordo com a issue #64
=> Implementado o metodo listar() da Classe NegocioAgendamento

src/main/java/br/edu/petpalacy/controller/ControllerAgendamento.java
=> #55 Criação da Classe ControllerAgendamento

pom.xml, src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioAgendamento.java, src/main/java/br/edu/ifpe/petpalacy/util/Mensagens.java, src/test/java/be/edu/ifpe/petpalacy/model/dao/PersistenciaDAOExceptoinTest.java, src/test/java/br/edu/ifpe/petpalacy/util/HibernateUtilTest.java
=> criação da classe Mensagens

src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioAgendamento.java, src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioEmpresa.java
@DanielCalado Eu tinha trocado as mensagens, mas agora ta legal observa a diferença.
=> Mensagens concertadas nas Classes NegocioAgendamento e NegocioEmpresa

src/main/java/br/edu/ifpe/petpalacy/controller/ControllerAgendamento.java
@DanielCalado De acordo com a issue #72
=> Movida a classe ControllerAgendamento

src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioCliente.java, src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioEmpresa.java, src/main/java/br/edu/ifpe/petpalacy/util/Mensagens.java
=> Colocado os validadores e criptografia

src/main/java/br/edu/ifpe/petpalacy/model/dao/PersistenciaDAO.java, src/main/java/br/edu/ifpe/petpalacy/model/repositorio/implementacao/RepositorioClienteImplDB.java, src/main/java/br/edu/ifpe/petpalacy/model/repositorio/implementacao/RepositorioEmpresaImplDB.java
=> Criado método buscaCpfCnpj

src/main/java/br/edu/ifpe/petpalacy/controller/ControllerCliente.java, src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioCliente.java, src/test/java/br/edu/ifpe/petpalacy/model/negocio/NegocioClienteTest.java
=> Ateração das classes negocioClliente e conrollerCliente

src/main/java/br/edu/ifpe/petpalacy/model/dao/PersistenciaDAO.java, src/main/java/br/edu/ifpe/petpalacy/model/repositorio/implementacao/RepositorioClienteImplDB.java, src/main/java/br/edu/ifpe/petpalacy/model/repositorio/implementacao/RepositorioEmpresaImplDB.java
=> Revert "Criado método buscaCpfCnpj"

src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioServico.java
=> classe negocio serviço

src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioAgendamento.java, src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioEmpresa.java
@DanielCalado, de acordo com a issue #97 .
=> #97 tratamento de exeções

src/main/java/br/edu/ifpe/petpalacy/controller/ControllerAgendamento.java, src/main/java/br/edu/ifpe/petpalacy/controller/ControllerEmpresa.java, src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioAgendamento.java, src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioEmpresa.java
@DanielCalado, de acordo com a issue #98 .
=> #98 adicionado mensagens e try catches.

src/main/java/br/edu/ifpe/petpalacy/Teste.java, src/main/java/br/edu/ifpe/petpalacy/model/repositorio/implementacao/RepositorioEmpresaImplDB.java, src/test/java/br/edu/ifpe/petpalacy/model/negocio/NegocioEmpresaTest.java, src/test/java/br/edu/ifpe/petpalacy/model/repositorio/implementacao/RepositorioClienteImplDBTest.java, src/test/java/br/edu/ifpe/petpalacy/model/repositorio/implementacao/RepositorioEmpresaImplDBTest.java
=> Crião dos testes negócioEmpresa e repositórioCliente

src/main/resources/hibernate.cfg.xml, src/test/java/br/edu/ifpe/petpalacy/model/repositorio/implementacao/RepositorioEmpresaImplDBTest.java, src/test/java/br/edu/ifpe/petpalacy/model/repositorio/implementacao/RepositorioServicoImplDBTest.java
Reverts ifpe-cti/petpalacy#109
=> Revert "Cancelado"

src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioCliente.java, src/test/java/br/edu/ifpe/petpalacy/model/negocio/NegocioClienteTest.java
=> NegocioCliente refeito

src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioCliente.java, src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioEmpresa.java, src/test/java/br/edu/ifpe/petpalacy/model/negocio/NegocioAgendamentoTest.java
=> correção nos testes de NegocioAgendamento

src/main/webapp/Servico/cadastro.xhtml
@DanielCalado, de acordo com a issue #132
=> #132 Pagina de cadastro do serviço.

src/main/webapp/Servico/alteraCadastro.xhtml
@DanielCalado, de acordo com a issue #132
=> #132 Pagina de alteração do serviço.

pom.xml, src/main/java/br/edu/ifpe/petpalacy/controller/ControllerAgendamento.java, src/main/java/br/edu/ifpe/petpalacy/controller/ControllerEmpresa.java, src/main/java/br/edu/ifpe/petpalacy/model/entidades/Agendamento.java, src/main/java/br/edu/ifpe/petpalacy/util/JavaMail.java, src/main/webapp/Cliente/agendarServico.xhtml, src/main/webapp/Empresa/alterarCadastro.xhtml, src/main/webapp/Empresa/meusAgendamentos.xhtml, src/main/webapp/templates/templateEmpresa.xhtml
=> criação de classe para enviar email

src/main/java/br/edu/ifpe/petpalacy/controller/ControllerCliente.java, src/main/java/br/edu/ifpe/petpalacy/controller/ControllerEmpresa.java, src/main/java/br/edu/ifpe/petpalacy/controller/ControllerServico.java, src/main/java/br/edu/ifpe/petpalacy/util/Mensagens.java, src/main/webapp/Cliente/cadastrar.xhtml, src/main/webapp/Empresa/alterarCadastroEmpresa.xhtml, src/main/webapp/Empresa/cadastrarEmpresa.xhtml, src/main/webapp/Empresa/cadastroServico.xhtml, src/main/webapp/Empresa/meusAgendamentos.xhtml, src/main/webapp/templates/templateCadastro.xhtml, src/main/webapp/visualizarEmpresa.xhtml, src/main/webapp/visualizarServicos.xhtml
=> Correções das mensagens de informações.

src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioAgendamento.java, src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioCliente.java, src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioEmpresa.java, src/main/java/br/edu/ifpe/petpalacy/model/negocio/NegocioServico.java, src/main/java/br/edu/ifpe/petpalacy/util/TratamentoException.java
=> #161 tratamento de erro
